force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <description>An object for storing Salesforce Files against.</description>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Offer Letter</fullName>
            </value>
            <value>
                <fullName>Cross-Cultural Activity (Photo/Documentation)</fullName>
            </value>
            <value>
                <fullName>Proof of Accreditation</fullName>
            </value>
            <value>
                <fullName>Proof of Insurance</fullName>
            </value>
            <value>
                <fullName>Workers&apos; Comp Verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentsServiceTest.cls
@isTest
private without sharing class DocumentsServiceTest {    
    @isTest 
    private static void getDocumentRecordByIdPositive(){
        // Get picklist values for the Document__c object's "Type__c" field
        Schema.DescribeFieldResult documentType = Document__c.Type__c.getDescribe();

        List<Schema.PicklistEntry> documentTypePicklistValues = documentType.getPicklistValues();
        String firstPicklistValue = documentTypePicklistValues[0].getValue();
        // Insert a Document__c record
        Document__c doc = (Document__c) new SObjectBuilder(Document__c.SobjectType)
        .put(Document__c.Type__c, firstPicklistValue)
        .create()
        .getRecord();  
        
        Test.startTest();
        Document__c document = DocumentsService.getDocumentRecordById(doc.Id);
        Test.stopTest();


        Id expectedId = doc.Id;
        Id actualId = document.Id;
        Assert.areEqual(expectedId, actualId, 'Expected Id ' + expectedId + ' but found ' + actualId);
    }
    @isTest 
    private static void getDocumentRecordByIdNegative(){
        // Insert a Document__c record
        Document__c doc = (Document__c) new SObjectBuilder(Document__c.SobjectType)
        .build()
        .provideDummyIds()
        .getRecord();
        
        Test.startTest();
        Document__c document = DocumentsService.getDocumentRecordById(doc.Id);
        Test.stopTest();


        Id expectedId = null;
        Id actualId = document?.Id;
        Assert.areEqual(expectedId, actualId, 'Expected null ' + ' but found ' + actualId);
    }
}